# Generated by Django 2.2.24 on 2022-02-12 15:21

from django.db import migrations

from phonenumbers import parse, is_valid_number


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone_number = parse(flat.owners_phonenumber, 'RU')
        if is_valid_number(pure_phone_number):
            flat.owner_pure_phone = pure_phone_number
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone, move_backward)
    ]
