# Generated by Django 2.2.24 on 2022-02-12 16:55

from django.db import migrations


def fill_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            pure_phone=flat.owner_pure_phone,
            defaults={'phonenumber': flat.owners_phonenumber}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220212_1936'),
    ]

    operations = [
        migrations.RunPython(fill_owner_model)
    ]
